### PR TITLE
Create detekt.yml

### PR DESCRIPTION
**Pull request by TimGels**

### CODE REVIEW

**Review by JohannesKauffmann — COMMENTED** [review]
Can you squash a04fae906e8f35ccd5857f6c8d1a2fea235e62e0 and 479ee283c1ee17894eb0be7b5c15ab0a032a0d9e together?

Also, if you're adding newlines to the unit test files, ExampleUnitTest also needs one.

**Comment by TimGels** [comment]
We most likely need a PR to reduce a lot of the items in the [baseline.xml ](https://github.com/TimGels/Camera-Security-System-Client/blob/866e56f41f7431796ccdf07d9cf9689c7e433e35/config/detekt/baseline.xml)

**Comment by TimGels** [comment]
> Can you squash [a04fae9](https://github.com/TimGels/Camera-Security-System-Client/commit/a04fae906e8f35ccd5857f6c8d1a2fea235e62e0) and [479ee28](https://github.com/TimGels/Camera-Security-System-Client/commit/479ee283c1ee17894eb0be7b5c15ab0a032a0d9e) together?
> 
> Also, if you're adding newlines to the unit test files, ExampleUnitTest also needs one.

  I will do the squashing later on, I'm still not finished with this PR. The reason detekt isnt complaining about the other test is because that one is added in the baseline.xml.

**Review by JohannesKauffmann — APPROVED** [review]

**Comment by JohannesKauffmann** [comment]
`app/build.gradle` and `config/detekt/detekt.yml` both have EOF characters on a non-empty line. Otherwise lgtm.

**Comment by TimGels** [comment]
> `app/build.gradle` and `config/detekt/detekt.yml` both have EOF characters on a non-empty line. Otherwise lgtm.

fixed

**Pull request merged**
